---
apiVersion: v1
kind: Pod
metadata:
  name: my-httpd
  labels:
    run: my-httpd
spec:
  containers:
  - name: my-httpd
    image: httpd
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-httpd-service
spec:
  selector:
    run: my-httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
